In [4]:
#pip install fredapi
from fredapi import Fred
import pandas as pd
import numpy as np

In [5]:
with open("API_KEY.txt") as txt:
    API_KEY = txt.read()

fred = Fred(api_key=API_KEY)

In [6]:
inflation_search = fred.search('U.S Inflation CPI', limit=5)
inflation_search.head()

,id,realtime_start,realtime_end,title,observation_start,observation_end,frequency,frequency_short,units,units_short,seasonal_adjustment,seasonal_adjustment_short,last_updated,popularity,notes
series id,,,,,,,,,,,,,,,
CPIAUCSL,CPIAUCSL,2023-03-08,2023-03-08,Consumer Price Index for All Urban Consumers: ...,1947-01-01,2023-01-01,Monthly,M,Index 1982-1984=100,Index 1982-1984=100,Seasonally Adjusted,SA,2023-02-14 07:41:49-06:00,95,The Consumer Price Index for All Urban Consume...
CPIAUCNS,CPIAUCNS,2023-03-08,2023-03-08,Consumer Price Index for All Urban Consumers: ...,1913-01-01,2023-01-01,Monthly,M,Index 1982-1984=100,Index 1982-1984=100,Not Seasonally Adjusted,NSA,2023-02-14 07:41:01-06:00,73,Handbook of Methods (https://www.bls.gov/opub/...
FPCPITOTLZGUSA,FPCPITOTLZGUSA,2023-03-08,2023-03-08,"Inflation, consumer prices for the United States",1960-01-01,2021-01-01,Annual,A,Percent,%,Not Seasonally Adjusted,NSA,2022-05-03 14:01:02-05:00,85,Inflation as measured by the consumer price in...
CORESTICKM159SFRBATL,CORESTICKM159SFRBATL,2023-03-08,2023-03-08,Sticky Price Consumer Price Index less Food an...,1967-12-01,2023-01-01,Monthly,M,Percent Change from Year Ago,% Chg. from Yr. Ago,Seasonally Adjusted,SA,2023-02-14 12:01:02-06:00,83,The Sticky Price Consumer Price Index (CPI) is...
CORESTICKM158SFRBATL,CORESTICKM158SFRBATL,2023-03-08,2023-03-08,Sticky Price Consumer Price Index less Food an...,1967-01-01,2023-01-01,Monthly,M,Percent Change at Annual Rate,% Chg. at Annual Rate,Seasonally Adjusted,SA,2023-02-14 12:01:02-06:00,47,The Sticky Price Consumer Price Index (CPI) is...

In [7]:
income_search = fred.search('Median Household Income in the United State', limit=5)
income_search.head()

,id,realtime_start,realtime_end,title,observation_start,observation_end,frequency,frequency_short,units,units_short,seasonal_adjustment,seasonal_adjustment_short,last_updated,popularity,notes
series id,,,,,,,,,,,,,,,
MEHOINUSA672N,MEHOINUSA672N,2023-03-08,2023-03-08,Real Median Household Income in the United States,1984-01-01,2021-01-01,Annual,A,2021 CPI-U-RS Adjusted Dollars,2021 CPI-U-RS Adjusted $,Not Seasonally Adjusted,NSA,2022-09-13 13:48:01-05:00,81,Household data are collected as of March. As ...
MEHOINUSA646N,MEHOINUSA646N,2023-03-08,2023-03-08,Median Household Income in the United States,1984-01-01,2021-01-01,Annual,A,Current Dollars,Current $,Not Seasonally Adjusted,NSA,2022-09-13 13:48:03-05:00,64,Household data are collected as of March. As ...
MEHOINUSCAA646N,MEHOINUSCAA646N,2023-03-08,2023-03-08,Median Household Income in California,1984-01-01,2021-01-01,Annual,A,Current Dollars,Current $,Not Seasonally Adjusted,NSA,2022-09-13 13:48:03-05:00,52,Household data are collected as of March. As ...
MEHOINUSNYA672N,MEHOINUSNYA672N,2023-03-08,2023-03-08,Real Median Household Income in New York,1984-01-01,2021-01-01,Annual,A,2021 CPI-U-RS Adjusted Dollars,2021 CPI-U-RS Adjusted $,Not Seasonally Adjusted,NSA,2022-09-13 13:48:04-05:00,41,Household data are collected as of March. Con...
MHICA06037A052NCEN,MHICA06037A052NCEN,2023-03-08,2023-03-08,Estimate of Median Household Income for Los An...,1989-01-01,2021-01-01,Annual,A,Dollars,$,Not Seasonally Adjusted,NSA,2022-12-21 09:38:03-06:00,39,The U.S. Census Bureau provides annual estimat...

In [8]:
cpi_us = fred.get_series(series_id='CPIAUCSL', observation_start="1990-01-01" ,observation_end="2020-01-01")
median_income_us = fred.get_series(series_id='MEHOINUSA646N', observation_start="1990-01-01" ,observation_end="2020-01-01")

cpi_us = cpi_us.to_frame(name="cpi_us")
cpi_us.reset_index(inplace=True)
cpi_us.rename( columns={"index" :"date"}, inplace=True )

median_income_us = median_income_us.to_frame(name="median_income_us")
median_income_us.reset_index(inplace=True)
median_income_us.rename( columns={"index" :"date"}, inplace=True )

In [9]:
cpi_us

          date   cpi_us
0   1990-01-01  127.500
1   1990-02-01  128.000
2   1990-03-01  128.600
3   1990-04-01  128.900
4   1990-05-01  129.100
..         ...      ...
356 2019-09-01  256.511
357 2019-10-01  257.244
358 2019-11-01  257.803
359 2019-12-01  258.616
360 2020-01-01  259.037

[361 rows x 2 columns]

In [10]:
data = pd.merge(cpi_us, median_income_us, how="left", on="date")
data.reset_index(drop=True)
data.head()

        date  cpi_us  median_income_us
0 1990-01-01   127.5           29943.0
1 1990-02-01   128.0               NaN
2 1990-03-01   128.6               NaN
3 1990-04-01   128.9               NaN
4 1990-05-01   129.1               NaN

In [11]:
data["real_mi_us"] = data["median_income_us"] * (data["cpi_us"][len(data["cpi_us"])-1]/data["cpi_us"])
data["per_change_real_mi"] = data["real_mi_us"].pct_change()*100
data["dif1_cpi"] = data.cpi_us.diff()
data["dif2_cpi"] = data.cpi_us.diff().diff()
data.head()

,date,cpi_us,median_income_us,real_mi_us,per_change_real_mi,dif1_cpi,dif2_cpi
0,1990-01-01,127.5,29943.0,60834.077576,NaN,NaN,NaN
1,1990-02-01,128.0,NaN,NaN,0.0,0.5,NaN
2,1990-03-01,128.6,NaN,NaN,0.0,0.6,0.1
3,1990-04-01,128.9,NaN,NaN,0.0,0.3,-0.3
4,1990-05-01,129.1,NaN,NaN,0.0,0.2,-0.1

In [13]:
data.to_csv(path_or_buf="./data/data.csv", index=False)